################################################################################
# OPEN SOURCE MODULE
# Remove the comment if you changed the build scripts!
################################################################################

version: "{build}"

# # Uncomment to debug via RDP
# init:
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

image: Visual Studio 2017

environment:
  NODE_VERSION: 8.9.4
  CONSUL_VERSION: 0.7.5
  TLS_UNPROTECTED: world

services:
  - mongodb

install:
  # Install Node.js
  - ps: Install-Product node $env:NODE_VERSION x64
  - npm install

build: off

test_script:
  - npm run bot
