name: Nightly

on:
  schedule:
    # 9pm every day
    - cron: 0 21 * * *

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_CI_TOKEN }}

jobs:
  Update-Build-Configuration:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        # Use personal access token for cloning (and later pushing) code
        token: ${{ secrets.GITHUB_CI_TOKEN }}

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        NODE_VERSION: ${{ env.NODE_VERSION }}

    - name: Cache Node.js modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm ci

    - name: Install yeoman
      run: npm install -g yo @sealsystems/generator-seal-node

    - name: Download hub
      run: |
        pushd /tmp
        curl -L -o hub.tgz https://github.com/github/hub/releases/download/v${HUB_VERSION}/hub-linux-amd64-${HUB_VERSION}.tgz
        tar -xzf hub.tgz
        mv ./hub-linux-amd64-${HUB_VERSION}/bin/hub hub
        popd

    - name: Update build config
      run: yo seal-node:bundle-update --force

    - name: Commit changes
      run: |
        git checkout -b nightly/update-build-configuration || git checkout nightly/update-build-configuration
        git add .
        # Remove package-lock.json from index
        git reset -- package-lock.json
        git commit -m "Update build configuration" || exit 0
        # Other files have also been changed, so we can include package-lock.json again
        git add package-lock.json && git commit --amend --no-edit
        git push --force -u origin nightly/update-build-configuration
        if [ -z "$(/tmp/hub pr list -h `git rev-parse --abbrev-ref HEAD`)" ]; then
          /tmp/hub pull-request -m "Update build configuration" --no-edit -r "scherermichael"
        fi
